config/routes.rb
Rails.application.routes.draw do
  resources :dyrektors
  resources :magazyniers
  resources :magazyns
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "magazyns#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dyrektor.rb
class Dyrektor < ApplicationRecord
  belongs_to :magazyn
end

app/models/magazyn.rb
class Magazyn < ApplicationRecord
  has_many :magazynier
  has_one :dyrektor
end

app/models/magazynier.rb
class Magazynier < ApplicationRecord
  belongs_to :magazyn
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dyrektors_controller.rb
class DyrektorsController < ApplicationController
  before_action :set_dyrektor, only: %i[ show edit update destroy ]

  # GET /dyrektors or /dyrektors.json
  def index
    @dyrektors = Dyrektor.all
  end

  # GET /dyrektors/1 or /dyrektors/1.json
  def show
  end

  # GET /dyrektors/new
  def new
    @dyrektor = Dyrektor.new
  end

  # GET /dyrektors/1/edit
  def edit
  end

  # POST /dyrektors or /dyrektors.json
  def create
    @dyrektor = Dyrektor.new(dyrektor_params)

    respond_to do |format|
      if @dyrektor.save
        format.html { redirect_to dyrektor_url(@dyrektor), notice: "Dyrektor was successfully created." }
        format.json { render :show, status: :created, location: @dyrektor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dyrektor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dyrektors/1 or /dyrektors/1.json
  def update
    respond_to do |format|
      if @dyrektor.update(dyrektor_params)
        format.html { redirect_to dyrektor_url(@dyrektor), notice: "Dyrektor was successfully updated." }
        format.json { render :show, status: :ok, location: @dyrektor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dyrektor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dyrektors/1 or /dyrektors/1.json
  def destroy
    @dyrektor.destroy

    respond_to do |format|
      format.html { redirect_to dyrektors_url, notice: "Dyrektor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dyrektor
      @dyrektor = Dyrektor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dyrektor_params
      params.require(:dyrektor).permit(:Name, :Surname, :Salary, :magazyn_id)
    end
end

app/controllers/magazyniers_controller.rb
class MagazyniersController < ApplicationController
  before_action :set_magazynier, only: %i[ show edit update destroy ]

  # GET /magazyniers or /magazyniers.json
  def index
    @magazyniers = Magazynier.all
  end

  # GET /magazyniers/1 or /magazyniers/1.json
  def show
  end

  # GET /magazyniers/new
  def new
    @magazynier = Magazynier.new
  end

  # GET /magazyniers/1/edit
  def edit
  end

  # POST /magazyniers or /magazyniers.json
  def create
    @magazynier = Magazynier.new(magazynier_params)

    respond_to do |format|
      if @magazynier.save
        format.html { redirect_to magazynier_url(@magazynier), notice: "Magazynier was successfully created." }
        format.json { render :show, status: :created, location: @magazynier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @magazynier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazyniers/1 or /magazyniers/1.json
  def update
    respond_to do |format|
      if @magazynier.update(magazynier_params)
        format.html { redirect_to magazynier_url(@magazynier), notice: "Magazynier was successfully updated." }
        format.json { render :show, status: :ok, location: @magazynier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @magazynier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazyniers/1 or /magazyniers/1.json
  def destroy
    @magazynier.destroy

    respond_to do |format|
      format.html { redirect_to magazyniers_url, notice: "Magazynier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazynier
      @magazynier = Magazynier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def magazynier_params
      params.require(:magazynier).permit(:Name, :Surname, :Salary, :Shift, :magazyn_id)
    end
end

app/controllers/magazyns_controller.rb
class MagazynsController < ApplicationController
  before_action :set_magazyn, only: %i[ show edit update destroy ]

  # GET /magazyns or /magazyns.json
  def index
    @magazyns = Magazyn.all
  end

  # GET /magazyns/1 or /magazyns/1.json
  def show
  end

  # GET /magazyns/new
  def new
    @magazyn = Magazyn.new
  end

  # GET /magazyns/1/edit
  def edit
  end

  # POST /magazyns or /magazyns.json
  def create
    @magazyn = Magazyn.new(magazyn_params)

    respond_to do |format|
      if @magazyn.save
        format.html { redirect_to magazyn_url(@magazyn), notice: "Magazyn was successfully created." }
        format.json { render :show, status: :created, location: @magazyn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @magazyn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazyns/1 or /magazyns/1.json
  def update
    respond_to do |format|
      if @magazyn.update(magazyn_params)
        format.html { redirect_to magazyn_url(@magazyn), notice: "Magazyn was successfully updated." }
        format.json { render :show, status: :ok, location: @magazyn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @magazyn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazyns/1 or /magazyns/1.json
  def destroy
    @magazyn.destroy

    respond_to do |format|
      format.html { redirect_to magazyns_url, notice: "Magazyn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazyn
      @magazyn = Magazyn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def magazyn_params
      params.require(:magazyn).permit(:City, :Street, :PostalCode, :Country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dyrektors_helper.rb
module DyrektorsHelper
end

app/helpers/magazyniers_helper.rb
module MagazyniersHelper
end

app/helpers/magazyns_helper.rb
module MagazynsHelper
end

app/views/dyrektors/_dyrektor.html.erb
<div id="<%= dom_id dyrektor %>">
  <p>
    <strong>Name:</strong>
    <%= dyrektor.Name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= dyrektor.Surname %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= dyrektor.Salary %>
  </p>

  <p>
    <strong>Magazyn:</strong>
    <%= dyrektor.magazyn_id %>
  </p>

</div>

app/views/dyrektors/_form.html.erb
<%= form_with(model: dyrektor) do |form| %>
  <% if dyrektor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dyrektor.errors.count, "error") %> prohibited this dyrektor from being saved:</h2>

      <ul>
        <% dyrektor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :Surname, style: "display: block" %>
    <%= form.text_field :Surname %>
  </div>

  <div>
    <%= form.label :Salary, style: "display: block" %>
    <%= form.text_field :Salary %>
  </div>

  <div>
    <%= form.label :magazyn_id, style: "display: block" %>
    <%= form.text_field :magazyn_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dyrektors/edit.html.erb
<h1>Editing dyrektor</h1>

<%= render "form", dyrektor: @dyrektor %>

<br>

<div>
  <%= link_to "Show this dyrektor", @dyrektor %> |
  <%= link_to "Back to dyrektors", dyrektors_path %>
</div>

app/views/dyrektors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dyrektorzy</h1>

<div id="dyrektors">
  <% @dyrektors.each do |dyrektor| %>
    <%= render dyrektor %>
    <p>
      <%= link_to "Show this dyrektor", dyrektor %>
    </p>
  <% end %>
</div>

<%= link_to "New dyrektor", new_dyrektor_path %>

app/views/dyrektors/new.html.erb
<h1>New dyrektor</h1>

<%= render "form", dyrektor: @dyrektor %>

<br>

<div>
  <%= link_to "Back to dyrektors", dyrektors_path %>
</div>

app/views/dyrektors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dyrektor %>

<div>
  <%= link_to "Edit this dyrektor", edit_dyrektor_path(@dyrektor) %> |
  <%= link_to "Back to dyrektors", dyrektors_path %>

  <%= button_to "Destroy this dyrektor", @dyrektor, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/magazyniers/_form.html.erb
<%= form_with(model: magazynier) do |form| %>
  <% if magazynier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(magazynier.errors.count, "error") %> prohibited this magazynier from being saved:</h2>

      <ul>
        <% magazynier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :Surname, style: "display: block" %>
    <%= form.text_field :Surname %>
  </div>

  <div>
    <%= form.label :Salary, style: "display: block" %>
    <%= form.text_field :Salary %>
  </div>

  <div>
    <%= form.label :Shift, style: "display: block" %>
    <%= form.text_field :Shift %>
  </div>

  <div>
    <%= form.label :magazyn_id, style: "display: block" %>
    <%= form.text_field :magazyn_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/magazyniers/_magazynier.html.erb
<div id="<%= dom_id magazynier %>">
  <p>
    <strong>Name:</strong>
    <%= magazynier.Name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= magazynier.Surname %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= magazynier.Salary %>
  </p>

  <p>
    <strong>Shift:</strong>
    <%= magazynier.Shift %>
  </p>

  <p>
    <strong>Magazyn:</strong>
    <%= magazynier.magazyn_id %>
  </p>

</div>

app/views/magazyniers/edit.html.erb
<h1>Editing magazynier</h1>

<%= render "form", magazynier: @magazynier %>

<br>

<div>
  <%= link_to "Show this magazynier", @magazynier %> |
  <%= link_to "Back to magazyniers", magazyniers_path %>
</div>

app/views/magazyniers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Magazynierzy</h1>

<div id="magazyniers">
  <% @magazyniers.each do |magazynier| %>
    <%= render magazynier %>
    <p>
      <%= link_to "Show this magazynier", magazynier %>
    </p>
  <% end %>
</div>

<%= link_to "New magazynier", new_magazynier_path %>

app/views/magazyniers/new.html.erb
<h1>New magazynier</h1>

<%= render "form", magazynier: @magazynier %>

<br>

<div>
  <%= link_to "Back to magazyniers", magazyniers_path %>
</div>

app/views/magazyniers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @magazynier %>

<div>
  <%= link_to "Edit this magazynier", edit_magazynier_path(@magazynier) %> |
  <%= link_to "Back to magazyniers", magazyniers_path %>

  <%= button_to "Destroy this magazynier", @magazynier, method: :delete %>
</div>

app/views/magazyns/_form.html.erb
<%= form_with(model: magazyn) do |form| %>
  <% if magazyn.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(magazyn.errors.count, "error") %> prohibited this magazyn from being saved:</h2>

      <ul>
        <% magazyn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :City, style: "display: block" %>
    <%= form.text_field :City %>
  </div>

  <div>
    <%= form.label :Street, style: "display: block" %>
    <%= form.text_field :Street %>
  </div>

  <div>
    <%= form.label :PostalCode, style: "display: block" %>
    <%= form.text_field :PostalCode %>
  </div>

  <div>
    <%= form.label :Country, style: "display: block" %>
    <%= form.text_field :Country %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/magazyns/_magazyn.html.erb
<div id="<%= dom_id magazyn %>">
  <h1><%= magazyn.City %> <%= magazyn.Street %></h1>
  <p>
    <strong>Postalcode:</strong>
    <%= magazyn.PostalCode %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= magazyn.Country %>
  </p>

</div>

app/views/magazyns/edit.html.erb
<h1>Editing magazyn</h1>

<%= render "form", magazyn: @magazyn %>

<br>

<div>
  <%= link_to "Show this magazyn", @magazyn %> |
  <%= link_to "Back to magazyns", magazyns_path %>
</div>

app/views/magazyns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Magazyny</h1>

<div id="magazyns">
  <% @magazyns.each do |magazyn| %>
    <%= render magazyn %>
    <p>
      <%= link_to "Show this magazyn", magazyn %>
    </p>
  <% end %>
</div>

<%= link_to "New magazyn", new_magazyn_path %>

app/views/magazyns/new.html.erb
<h1>New magazyn</h1>

<%= render "form", magazyn: @magazyn %>

<br>

<div>
  <%= link_to "Back to magazyns", magazyns_path %>
</div>

app/views/magazyns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @magazyn %>

<div>
  <%= link_to "Edit this magazyn", edit_magazyn_path(@magazyn) %> |
  <%= link_to "Back to magazyns", magazyns_path %>

  <%= button_to "Destroy this magazyn", @magazyn, method: :delete %>
</div>